spring.application.name=user-service
server.port=${PORT:8081}

# PostgreSQL connection.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# show SQL in logs for development (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (development defaults) - must be long enough for HS256 (>=32 bytes)
app.jwt.secret=changeit-dev-secret-please-change-0123456789ABCDEF
app.jwt.expiration-ms=3600000
