name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - 'Frontend/**'
  pull_request:
    branches: [main]
    paths:
      - 'Frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: Frontend/package-lock.json
      - name: Install & Build
        run: |
          npm install
          npm run build
        working-directory: frontend-react # Đảm bảo trỏ đúng thư mục chứa React

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend-react/dist # Thư mục chứa file index.html sau khi build
          branch: gh-pages # GitHub sẽ tự tạo nhánh này cho bạn
